repos:
  - repo: https://github.com/gitguardian/ggshield
    rev: v1.12.0
    hooks:
      - id: ggshield
        language_version: python3
        stages: [commit]

  - repo: https://github.com/psf/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.10