version: "3"
services:
  postgres:
    image: "postgres"
    container_name: "postgres_datagen"
    environment:
      - POSTGRES_USER=datagen
      - POSTGRES_PASSWORD=datagen
      - POSTGRES_DB=datagen
    ports:
      - "127.0.0.1:54321:5432"

  rabbit:
    image: rabbitmq:management
    container_name: rabbitmq__datagen
    ports:
      - "127.0.0.1:5672:5672"
      - "127.0.0.1:15672:15672"
    mem_limit: "1000M"