# Generated by Django 4.0.4 on 2022-05-18 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "schema",
            "0001_squashed_0012_rename_num_records_generateddata_num_rows_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="schema",
            name="modified",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
