# Generated by Django 4.0.4 on 2022-05-05 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("schema", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="schema",
            name="column_separator",
            field=models.CharField(default=",", max_length=1),
        ),
        migrations.AddField(
            model_name="schema", name="quotechar", field=models.CharField(default='"', max_length=1)
        ),
    ]
