# Generated by Django 4.0.4 on 2022-05-05 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("schema", "0002_schema_column_separator_schema_quotechar")]

    operations = [
        migrations.RenameField(model_name="schema", old_name="fields", new_name="fields_json")
    ]
