# Generated by Django 4.0.4 on 2022-05-20 09:10

from django.apps.registry import Apps
from django.contrib.auth.models import Permission
from django.contrib.contenttypes.models import ContentType
from django.db import migrations
from django.db.backends.base.schema import (
    BaseDatabaseSchemaEditor as SchemaEditor,
)
from django.db.models import Model


def add_permission(apps: Apps, schema_editor: SchemaEditor) -> None:
    GeneratedData: Model = apps.get_model("schema", "GeneratedData")  # type: ignore
    content_type = ContentType.objects.get_for_model(GeneratedData)
    Permission.objects.create(
        codename="unlimited_generation",
        name="Can generate unlimited data",
        content_type=content_type,
    )


def drop_permission(apps: Apps, schema_editor: SchemaEditor) -> None:
    GeneratedData: Model = apps.get_model("schema", "GeneratedData")  # type: ignore
    content_type = ContentType.objects.get_for_model(GeneratedData)
    Permission.objects.get(
        codename="unlimited_generation",
        name="Can generate unlimited data",
        content_type=content_type,
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("schema", "0002_schema_modified"),
    ]
    operations = [
        migrations.RunPython(add_permission, drop_permission),
    ]
