# Generated by Django 4.0.4 on 2022-05-20 09:10

from django.db import migrations
from django.contrib.auth.models import Permission
from django.contrib.contenttypes.models import ContentType


def add_permission(apps, schema_editor):
    GeneratedData = apps.get_model("schema", "GeneratedData")
    content_type = ContentType.objects.get_for_model(GeneratedData)
    Permission.objects.create(
        codename="unlimited_generation",
        name="Can generate unlimited data",
        content_type=content_type,
    )


def drop_permission(apps, schema_editor):
    GeneratedData = apps.get_model("schema", "GeneratedData")
    content_type = ContentType.objects.get_for_model(GeneratedData)
    Permission.objects.get(
        codename="unlimited_generation",
        name="Can generate unlimited data",
        content_type=content_type,
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("schema", "0002_schema_modified"),
    ]

    operations = [
        migrations.RunPython(add_permission, drop_permission),
    ]
