# Generated by Django 4.0.4 on 2022-05-06 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("schema", "0003_rename_fields_schema_fields_json")]

    operations = [
        migrations.RenameField(model_name="schema", old_name="fields_json", new_name="fields")
    ]
