# Generated by Django 4.0.4 on 2022-05-05 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("schema", "0004_rename_fields_json_schema_fields")]

    operations = [
        migrations.AlterField(
            model_name="generateddata",
            name="schema",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="generated_data",
                to="schema.schema",
            ),
        )
    ]
