# Generated by Django 4.0.4 on 2022-06-19 12:05
import django.core.validators
import django.db.models.deletion
from django.apps.registry import Apps
from django.db import migrations, models
from django.db.backends.base.schema import (
    BaseDatabaseSchemaEditor as SchemaEditor,
)


def move_schema_fields_to_model_columns(
    apps: Apps, schema_editor: SchemaEditor
) -> None:
    schema = apps.get_model("schema", "schema")
    from ..models import BaseColumn

    typed_columns = {
        column.type: column for column in BaseColumn.__subclasses__()
    }

    for schema_instance in schema.objects.all():
        for column in schema_instance.fields:  # type: ignore[attr-defined]
            f_type = column.pop("f_type")
            column.update(column.pop("f_params"))
            typed_columns[f_type].objects.create(
                **column, schema_id=schema_instance.pk
            )


class Migration(migrations.Migration):

    replaces = [
        (
            "schema",
            "0006_remove_schema_fields_randomintcolumn_namecolumn_squashed_0007_remove_randomintcolumn_max_and_more",
        ),
        ("schema", "0007_alter_namecolumn_unique_together_and_more"),
        ("schema", "0008_alter_randomintcolumn_max_alter_randomintcolumn_min"),
        ("schema", "0009_alter_namecolumn_unique_together_and_more"),
        ("schema", "0010_alter_addressfieldform_name_and_more"),
        ("schema", "0011_rename_addressfieldform_addresscolumn_and_more"),
    ]

    dependencies = [
        ("schema", "0005_alter_dataset_schema"),
    ]

    operations = [
        migrations.CreateModel(
            name="NameColumn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField(default=1)),
                (
                    "name",
                    models.CharField(
                        max_length=255,
                        validators=[
                            django.core.validators.MinLengthValidator(1)
                        ],
                    ),
                ),
                (
                    "schema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="schema.schema",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "unique_together": set(),
            },
        ),
        migrations.CreateModel(
            name="RandomIntColumn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField(default=1)),
                (
                    "name",
                    models.CharField(
                        max_length=255,
                        validators=[
                            django.core.validators.MinLengthValidator(1)
                        ],
                    ),
                ),
                (
                    "schema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="schema.schema",
                    ),
                ),
                ("max", models.IntegerField(default=100)),
                ("min", models.IntegerField(default=1)),
            ],
            options={
                "abstract": False,
                "unique_together": set(),
            },
        ),
        migrations.CreateModel(
            name="AddressColumn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255,
                        validators=[
                            django.core.validators.MinLengthValidator(1)
                        ],
                    ),
                ),
                ("order", models.IntegerField(default=1)),
                (
                    "schema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="schema.schema",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CompanyColumn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255,
                        validators=[
                            django.core.validators.MinLengthValidator(1)
                        ],
                    ),
                ),
                ("order", models.IntegerField(default=1)),
                (
                    "schema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="schema.schema",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DateColumn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255,
                        validators=[
                            django.core.validators.MinLengthValidator(1)
                        ],
                    ),
                ),
                ("order", models.IntegerField(default=1)),
                (
                    "schema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="schema.schema",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DomainColumn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255,
                        validators=[
                            django.core.validators.MinLengthValidator(1)
                        ],
                    ),
                ),
                ("order", models.IntegerField(default=1)),
                (
                    "schema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="schema.schema",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EmailColumn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255,
                        validators=[
                            django.core.validators.MinLengthValidator(1)
                        ],
                    ),
                ),
                ("order", models.IntegerField(default=1)),
                (
                    "schema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="schema.schema",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="JobColumn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255,
                        validators=[
                            django.core.validators.MinLengthValidator(1)
                        ],
                    ),
                ),
                ("order", models.IntegerField(default=1)),
                (
                    "schema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="schema.schema",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PhoneNumberColumn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255,
                        validators=[
                            django.core.validators.MinLengthValidator(1)
                        ],
                    ),
                ),
                ("order", models.IntegerField(default=1)),
                (
                    "schema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="schema.schema",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SentencesColumn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255,
                        validators=[
                            django.core.validators.MinLengthValidator(1)
                        ],
                    ),
                ),
                ("order", models.IntegerField(default=1)),
                (
                    "nb_min",
                    models.IntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100000),
                        ],
                    ),
                ),
                (
                    "nb_max",
                    models.IntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100000),
                        ],
                    ),
                ),
                (
                    "schema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="schema.schema",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RunPython(move_schema_fields_to_model_columns),
        migrations.RemoveField(
            model_name="schema",
            name="fields",
        ),
    ]
