# Generated by Django 4.0.4 on 2022-06-12 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "schema",
            "0006_remove_schema_fields_randomintcolumn_namecolumn_squashed_0007_remove_randomintcolumn_max_and_more",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="namecolumn",
            unique_together={("id", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="randomintcolumn",
            unique_together={("id", "name")},
        ),
    ]
