# Generated by Django 4.0.4 on 2022-06-14 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schema", "0007_alter_namecolumn_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="randomintcolumn",
            name="max",
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name="randomintcolumn",
            name="min",
            field=models.IntegerField(default=1),
        ),
    ]
