# Generated by Django 4.0.4 on 2022-05-08 16:50

import datagen.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("schema", "0007_alter_generateddata_schema")]

    operations = [
        migrations.RemoveField(model_name="generateddata", name="slug"),
        migrations.AddField(
            model_name="generateddata",
            name="file",
            field=models.FileField(
                null=True, storage=datagen.storage_backends.PrivateMediaStorage(), upload_to=""
            ),
        ),
    ]
