# Generated by Django 4.0.4 on 2022-05-08 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0008_remove_generateddata_slug_generateddata_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generateddata',
            name='generation_complete',
        ),
    ]
