# Generated by Django 4.0.4 on 2022-05-17 12:09

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("schema", "0011_alter_generateddata_created")]

    operations = [
        migrations.RenameField(
            model_name="generateddata", old_name="num_records", new_name="num_rows"
        ),
        migrations.AlterField(
            model_name="generateddata",
            name="file",
            field=models.FileField(
                null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to=""
            ),
        ),
    ]
