name: CI

on: 
  workflow_dispatch:
  pull_request:
      branches: [master]

jobs:
  Run-tests-and-gather-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.5'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install Poetry
        run: python -m pip install poetry

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: poetry install

      - name: Run formatter
        run: |
          source "$(poetry env info -p)/bin/activate"
          make format

      - name: Start PostgreSQL and RabbitMQ (docker compose)
        run: docker compose up -d

      - name: Run the tests with coverage
        run: |
          source "$(poetry env info -p)/bin/activate"
          make coverage

      - name: Print out coverage report
        run: |
          source "$(poetry env info -p)/bin/activate"
          coverage report

      - name: Commit coverage.xml to be usable by the badge
        run: |
          git config --local user.email "$(git log --format='%ae' HEAD^!)"
          git config --local user.name "$(git log --format='%an' HEAD^!)"
          git checkout ${ GITHUB_REF_NAME }
          git add .coverage/coverage.xml
          git commit -m "Update coverage"
          git push


  Security-check-CodeQl:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false

    steps:
    - name: Set up python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10.5'
      
    - name: Checkout repository
      uses: actions/checkout@v3

    # Initializes the CodeQL tools for scanning.
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: python
        setup-python-dependencies: true

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2