name: CI
on: 
  workflow_dispatch:
  push:
      branches: [master]
  pull_request:
      branches: [master]

jobs:
  Run-tests-and-gather-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Set up python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install Poetry
        run: python -m pip install poetry

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: poetry install

      - name: Run formatter
        run: |
          source "$(poetry env info -p)/bin/activate"
          make format

      - name: Start PostgreSQL and RabbitMQ (docker compose)
        run: docker compose up -d

      - name: Run the tests with coverage
        run: |
          source "$(poetry env info -p)/bin/activate"
          make coverage

      # TODO: add coverage label
      - name: Print out coverage report
        run: |
          source "$(poetry env info -p)/bin/activate"
          coverage report
