name: CI

on: 
  workflow_dispatch:
  pull_request:
      branches: [master]

jobs:
  Run-tests-and-gather-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
    
      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.5'
          cache: 'poetry'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install Poetry
        run: python -m pip install poetry

      - name: Install dependencies
        run: poetry install

      - name: Run formatter check
        run: |
          source "$(poetry env info -p)/bin/activate"
          make format

      - name: Run mypy typing checker
        run: |
          source "$(poetry env info -p)/bin/activate"
          make mypy

      - name: Start PostgreSQL and RabbitMQ (docker compose)
        run: docker compose up -d

      - name: Run the tests with coverage
        run: |
          source "$(poetry env info -p)/bin/activate"
          make coverage

      - name: Print out coverage report and move covinfo
        run: |
          source "$(poetry env info -p)/bin/activate"
          coverage report
          mv .coverage/coverage.xml .coverage/coverage_public.xml

      - name: Commit coverage_public.xml
        if: ${{ github.event_name == 'pull_request' }}
        uses: EndBug/add-and-commit@v9.0.0
        with:
          add: .coverage/coverage_public.xml
          commit: --signoff
          message: Update coverage
          pathspec_error_handling: exitImmediately
          push: true


  Security-check-CodeQl:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false

    steps:
    - name: Set up python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10.5'
      
    - name: Checkout repository
      uses: actions/checkout@v3

    # Initializes the CodeQL tools for scanning.
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: python
        setup-python-dependencies: true

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
