name: Heroku Deploy

on:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  deploy_to_heroku:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: akhileshns/heroku-deploy@v3.12.12 
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: datagen-challenge 
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          dontautocreate: true
          branch: master
